routes/web.php
<?php

use App\Http\Controllers\Admin\BerandaController;
use App\Http\Controllers\Admin\BeritaController;
use App\Http\Controllers\Admin\CalonSiswaController;
use App\Http\Controllers\Admin\DataSiswaController;
use App\Http\Controllers\Admin\DetailPaketSoalController;
use App\Http\Controllers\Admin\HasilController;
use App\Http\Controllers\Admin\JurusanController;
use App\Http\Controllers\Admin\KeuanganController;
use App\Http\Controllers\Admin\LaporanController;
use App\Http\Controllers\Admin\MasterController;
use App\Http\Controllers\Admin\PaketSoalController;
use App\Http\Controllers\Admin\PendataanAssetController;
use App\Http\Controllers\Admin\PengaturanController;
use App\Http\Controllers\Admin\PersuratanController;
use App\Http\Controllers\Admin\ProfilController;
use App\Http\Controllers\Admin\TestController;
use App\Http\Controllers\Admin\TokenController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\User\BerandaController as UserBerandaController;
use Illuminate\Support\Facades\Route;
use Symfony\Component\HttpKernel\Profiler\Profile;

Route::get('/', function () {
    return redirect()->route('web.beranda');
});

Route::controller(TestController::class)->prefix('test')->name('test.')->group(function () {
    Route::get('/mulai', 'index')->name('index');
    Route::post('/login', 'login')->name('login');
    Route::get('/{token}/{name}/{kelas}/{jurusan}', 'test')->name('test');
    Route::post('/store', 'store')->name('store');
});

Route::controller(UserBerandaController::class)->name('web.')->group(function () {
    Route::get('/', 'index')->name('beranda');
    Route::get('/berita', 'berita')->name('berita');
    Route::get('/data-siswa', 'dataSiswa')->name('dataSiswa');
    Route::get('/berita/{name}', 'lihat_berita')->name('berita.lihat');
    Route::get('/ppdb', 'ppdb')->name('ppdb');
    Route::post('/ppdb/store', 'ppdb_store')->name('ppdb.store');
    Route::get('/ppdb/berhasil-mendaftar/{name}/{id}', 'ppdb_detail')->name('ppdb.detail');
    Route::get('/ppdb/print/{name}/{id}', 'ppdb_print')->name('ppdb.print');
    Route::get('/ppdb/cek-pendaftaran', 'cek_ppdb')->name('ppdb.check');
    Route::get('/ppdb/kartu-lulus/{name}/{id}', 'ppdb_kartu_lulus')->name('ppdb.kartu.lulus');
    Route::get('/ppdb/kartu-lulus/{name}/{id}/print', 'ppdb_kartu_lulus_print')->name('ppdb.kartu.lulus.print');
    Route::get('/ppdb/test', 'test_ppdb')->name('ppdb.test');
});

Route::controller(LoginController::class)->name('auth.')->group(function () {
    Route::get('/login', 'login')->name('login.form');
    Route::post('/login', 'validation')->name('login.validation');
    Route::get('/logout', 'logout')->name('logout');
});

Route::prefix('admin')->name('admin.')->middleware(['auth'])->group(function () {
    // MIDDLEWARE AUTH
    Route::controller(BerandaController::class)->prefix('beranda')->name('beranda.')->group(function () {
        Route::get('/', 'index')->name('index');
    });
    Route::controller(LaporanController::class)->prefix('laporan')->name('laporan.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::get('/print', 'print')->name('print');
    });
    Route::controller(DataSiswaController::class)->prefix('data-siswa')->name('siswa.')->group(function () {
        Route::get('/', 'index')->name('index');
    });
    // END MIDDLEWARE AUTH

    // ADMIN
    Route::controller(UserController::class)->middleware(['user_akses:admin'])->prefix('akun-guru')->name('guru.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::post('/store', 'store')->name('store');
        Route::get('/{id}/destroy', 'destroy')->name('destroy');
        Route::post('/update', 'update')->name('update');
        Route::post('/update/password', 'change_password')->name('update.password');
    });
    // END ADMIN

    // PERSURATAN
    Route::controller(PersuratanController::class)->middleware(['user_akses:admin,persuratan'])->prefix('surat')->name('surat.')->group(function () {
        Route::prefix('diterima')->name('masuk.')->group(function () {
            Route::get('/', 'index_surat_masuk')->name('index');
            Route::get('/{id}/destroy', 'destroy_surat_masuk')->name('destroy');
            Route::get('/{id}/destroy-file', 'destroy_file_surat_masuk')->name('destroy.file');
            Route::get('/tambah-surat-masuk', 'create_surat_masuk')->name('create');
            Route::post('/store', 'store_surat_masuk')->name('store');
            Route::get('/{id}/edit', 'edit_surat_masuk')->name('edit');
            Route::post('/update', 'update_surat_masuk')->name('update');
        });
        Route::prefix('dikirim')->name('keluar.')->group(function () {
            Route::get('/', 'index_surat_keluar')->name('index');
            Route::get('/tambah-surat-keluar', 'create_surat_keluar')->name('create');
            Route::get('/{id}/destroy', 'destroy_surat_keluar')->name('destroy');
            Route::get('/{id}/destroy-file', 'destroy_file_surat_keluar')->name('destroy.file');
            Route::get('/{id}/edit', 'edit_surat_keluar')->name('edit');
            Route::post('/update', 'update_surat_keluar')->name('update');
            Route::get('/tambah-surat-keluar', 'create_surat_keluar')->name('create');
            Route::post('/store', 'store_surat_keluar')->name('store');
        });
    });
    Route::controller(PendataanAssetController::class)->middleware(['user_akses:admin,persuratan'])->prefix('aset')->name('aset.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::get('/{id}/edit', 'edit')->name('edit');
        Route::post('/update', 'update')->name('update');
        Route::get('/{id}/destroy', 'destroy')->name('destroy');
        Route::get('/data-aset-baru', 'create')->name('create');
        Route::post('/store', 'store')->name('store');
        Route::get('/{id}/destroy/gambar_1', 'gambar_1_destory')->name('destory.gambar_1');
        Route::get('/{id}/destroy/gambar_2', 'gambar_2_destory')->name('destory.gambar_2');
        Route::get('/{id}/destroy/gambar_3', 'gambar_3_destory')->name('destory.gambar_3');
    });
    // END PERSURATAN

    // PENGELOLA WEB
    Route::prefix('artikel.')->name('artikel.')->middleware(['user_akses:pengelola_web,admin'])->group(function () {
        Route::controller(BeritaController::class)->prefix('berita')->name('berita.')->group(function () {
            Route::get('/', 'index')->name('index');
            Route::get('/tulis-berita', 'create')->name('create');
            Route::post('/store', 'store')->name('store');
            Route::get('/{id}/destroy', 'destroy')->name('destroy');
            Route::get('/{id}/edit', 'edit')->name('edit');
            Route::post('/{id}/update', 'update')->name('update');
            Route::get('/{id}/destroy/thumbnail', 'thumbnail_destory')->name('destory.thumbnail');
        });
        Route::controller(JurusanController::class)->prefix('peminatan')->name('peminatan.')->group(function () {
            Route::get('/', 'index')->name('index');
            Route::get('/tulis-peminatan', 'create')->name('create');
            Route::post('/store', 'store')->name('store');
            Route::get('/{id}/destroy', 'destroy')->name('destroy');
            Route::get('/{id}/edit', 'edit')->name('edit');
            Route::post('/{id}/update', 'update')->name('update');
            Route::get('/{id}/destroy/thumbnail', 'thumbnail_destory')->name('destory.thumbnail');
        });
        Route::controller(ProfilController::class)->prefix('profil')->name('profil.')->group(function () {
            Route::get('/', 'index')->name('index');
            Route::post('/{id}/update', 'update')->name('update');
            Route::get('/{id}/destroy/thumbnail', 'thumbnail_destory')->name('destory.thumbnail');
        });
    });
    Route::controller(PengaturanController::class)->middleware(['user_akses:pengelola_web,admin,ppdb'])->prefix('pengaturan')->name('pengaturan.')->group(function () {
        Route::get('/instansi', 'instansi')->name('instansi');
        Route::post('/instansi/update', 'instansi_update')->name('instansi.update');
        Route::get('/logo-instansi/destory', 'logo_instansi_destory')->name('instansi.destory.logo');
        Route::get('/foto-carousel-1/destory', 'foto_carousel_1_destory')->name('instansi.destory.carousel_1');
        Route::get('/foto-carousel-2/destory', 'foto_carousel_2_destory')->name('instansi.destory.carousel_2');
        Route::get('/foto-carousel-3/destory', 'foto_carousel_3_destory')->name('instansi.destory.carousel_3');
        Route::get('/foto-kepala/destory', 'foto_kepala_destory')->name('instansi.destory.foto_kepala');
        Route::get('/thumbnail-visi-misi/destory', 'thumbnail_visi_misi_destory')->name('instansi.destory.thumbnail_visi_misi');
    });
    Route::controller(MasterController::class)->middleware(['user_akses:pengelola_web,admin'])->prefix('master')->name('master.')->group(function () {
        Route::prefix('jurusan')->name('jurusan.')->group(function () {
            Route::get('/', 'index_jurusan')->name('index');
            Route::post('/store', 'store_jurusan')->name('store');
            Route::get('/{id}/destroy', 'destroy_jurusan')->name('destroy');
            Route::post('/update', 'update_jurusan')->name('update');
        });
        Route::prefix('kategori')->name('kategori.')->group(function () {
            Route::get('/', 'index_kategori')->name('index');
            Route::post('/store', 'store_kategori')->name('store');
            Route::post('/update', 'update_kategori')->name('update');
            Route::get('/{id}/destroy', 'destroy_kategori')->name('destroy');
        });
    });
    // END PENGELOLA WEB

    // PANITIA PPDB
    Route::middleware(['user_akses:ppdb,admin'])->group(function () {

resources/views/admin/akun_guru/index.blade.php
@extends('layouts.dasboard')
@section('css')
    <style></style>
@endsection
@section('script')
    <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.12.1/js/dataTables.bootstrap5.min.js"></script>
    <script>
        $('#data-table').DataTable({
            responsive: true,
            pageLength: 10,
            lengthMenu: [[10, 50, 100, -1], [10, 50, 100, "Semua"]],
            paging: true,
        });
        function dataModal(data){
            console.log(JSON.parse(data))
            var data = JSON.parse(data)
            $('#id_user').val(data.id)
            $('#name').val(data.name)
            $('#email').val(data.email)
            $('#status').val(data.status).change()
            $('#role').val(data.role).change()
        }
        function dataModalPassword(data){
            console.log(JSON.parse(data))
            var data = JSON.parse(data)
            $('#id_user_password').val(data.id)
        }
    </script>
@endsection
@section('content')
<div class="row mb-3">
    <div class="col-12">
        <h3 class="mb-4">Akun Guru</h3>
    </div>
</div>
<div class="row">
    <div class="col-12 col-md-4 col-lg-4 order-1 order-md-2 order-lg-2 mb-3">
        <div class="card">
            <div class="card-header">
                <h4 class="form-label mb-2">Tambah data</h4>
            </div>
            <div class="card-body">
                <form class="forms-sample" action="{{ route('admin.guru.store') }}" method="POST">
                    @csrf
                    <input type="hidden" name="id">
                    <div class="form-group">
                        <label class="form-label">
                            Nama Pengguna
                            <span class="text-danger"> *</span>
                        </label>
                        <input type="text" class="form-control mb-3" value="{{ old('name') }}" name="name" placeholder="nama pengguna ..." autofocus style="border-radius: 5px !important">
                    </div>
                    <div class="row">
                        <div class="col-12 col-md-6 col-lg-6">
                            <div class="form-group">
                                <label class="form-label w-100">
                                    Akses Menu
                                    <span class="text-danger"> *</span>
                                </label>
                                <select class="form-control mb-3 select-2 w-100" name="role">
                                    @foreach (config('constant.roles') as $key => $val)
                                        <option value="{{ $key }}" {{ $key == old('role') ? 'selected' : '' }}>{{ $val }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="col-12 col-md-6 col-lg-6">
                            <div class="form-group">
                                <label class="form-label w-100">
                                    Status
                                    <span class="text-danger"> *</span>
                                </label>
                                <select class="form-control mb-3 select-2 w-100" name="status">
                                    @foreach (config('constant.status') as $key => $val)
                                        <option value="{{ $key }}" {{ $key == old('status') ? 'selected' : '' }}>{{ $val }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-label">
                            Email
                            <span class="text-danger"> *</span>
                        </label>
                        <input type="email" class="form-control mb-3" name="email" value="{{ old('email') }}" placeholder="alamat email ..." autofocus style="border-radius: 5px !important">
                    </div>
                    <div class="form-group">
                        <label class="form-label">
                            Kata Sandi (min. 8 karakter)
                            <span class="text-danger"> *</span>
                        </label>
                        <input type="password" class="form-control mb-3" name="password" value="{{ old('password') }}" placeholder="kata sandi ..." autofocus style="border-radius: 5px !important">
                    </div>
                    <button type="submit" class="btn btn-primary mr-2">Tambah</button>
                </form>
            </div>
        </div>
    </div>
    <div class="col-12 col-md-8 col-lg-8 order-2 order-md-1 order-lg-1 mb-3">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    <table id="data-table" class="table table-hover table-bordered" style="width: 100% !important">
                        <thead>
                            <tr>
                                <th class="text-center" style="width: 30px !important;">No</th>
                                <th>Nama</th>
                                <th>Email</th>
                                <th>Akses Menu</th>
                                <th>Status</th>
                                <th class="text-center" style="width: 150px">Opsi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($data as $index => $val)
                                <tr>
                                    <td>{{ ++$index }}</td>
                                    <td>{{ $val->name }}</td>
                                    <td>{{ $val->email  }}</td>
                                    <td>{{ getRole($val->role) }}</td>
                                    <td>{{ getStatus($val->status) }}</td>
                                    <td>
                                        <button type="button" class="btn btn-primary br-1 px-1 mb-1"
                                            title="Edit {{ $val->nama_jurusan }}"
                                            onclick="dataModal('{{ json_encode($val) }}')"
                                            data-toggle="modal" data-target="#modalEdit"
                                            style="height: 30px !important; min-width: 30px !important">
                                            <i data-feather="edit" width="13"></i>
                                        </button>
                                        <button type="button" class="btn btn-warning br-1 px-1 mb-1"
                                            title="Ganti Password {{ $val->nama_jurusan }}"
                                            onclick="dataModalPassword('{{ json_encode($val) }}')"
                                            data-toggle="modal" data-target="#modalPassword"
                                            style="height: 30px !important; min-width: 30px !important">
                                            <i data-feather="key" width="13"></i>
                                        </button>
                                        <button type="button" class="btn btn-danger br-1 px-1 mb-1"
                                            title="Hapus {{ $val->name }}"
                                            onclick="alert_confirm('Hapus {{ $val->name }}?','{{ route('admin.guru.destroy',['id'=> $val->id]) }}','Hapus','Batal')"
                                            style="height: 30px !important; min-width: 30px !important">
                                            <i data-feather="trash" width="13"></i>
                                        </button>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal Edit -->
<div class="modal fade" id="modalPassword" tabindex="-1" role="dialog" aria-labelledby="modalPasswordLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content br-2">
            <form class="forms-sample" action="{{ route('admin.guru.update.password') }}" method="POST">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalPasswordLabel">Reset Kata sandi</h5>
                </div>
                <div class="modal-body">
                    @csrf
                    <input type="hidden" id="id_user_password" name="id">
                    <div class="form-group">
                        <label class="form-label">
                            Kata Sandi (min. 8 karakter)
                            <span class="text-danger"> *</span>
                        </label>
                        <input type="password" class="form-control mb-3" name="password" placeholder="kata sandi ..." autofocus style="border-radius: 5px !important">
                    </div>
                    <div class="form-group">
                        <label class="form-label">
                            Ulangi Kata Sandi (min. 8 karakter)
                            <span class="text-danger"> *</span>
                        </label>
                        <input type="password" class="form-control mb-3" name="ulang_password" placeholder="ulangi kata sandi ..." autofocus style="border-radius: 5px !important">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Tutup</button>
                    <button type="submit" class="btn btn-primary">Simpan</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- End Modal Edit -->

<!-- Modal Edit -->
<div class="modal fade" id="modalEdit" tabindex="-1" role="dialog" aria-labelledby="modalEditLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content br-2">
            <form class="forms-sample" action="{{ route('admin.guru.update') }}" method="POST">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalEditLabel">Edit Akun Guru</h5>
                </div>
                <div class="modal-body">
                    @csrf
                    <input type="hidden" id="id_user" name="id">
                    <div class="form-group">
                        <label class="form-label">
                            Nama Pengguna
                            <span class="text-danger"> *</span>
                        </label>
                        <input type="text" class="form-control mb-3" id="name" name="name" placeholder="nama pengguna ..." autofocus style="border-radius: 5px !important">
                    </div>
                    <div class="row">
                        <div class="col-12 col-md-6 col-lg-6">
                            <div class="form-group">
                                <label class="form-label w-100">
                                    Akses Menu
                                    <span class="text-danger"> *</span>
                                </label>
                                <select class="form-control mb-3 select-2" name="role" id="role" style="width: 100% !important">
                                    @foreach (config('constant.roles') as $key => $val)
                                        <option value="{{ $key }}">{{ $val }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="col-12 col-md-6 col-lg-6">
                            <div class="form-group">
                                <label class="form-label w-100">
                                    Status
                                    <span class="text-danger"> *</span>
                                </label>
                                <select class="form-control mb-3 select-2" name="status" id="status" style="width: 100% !important">
                                    @foreach (config('constant.status') as $key => $val)
                                        <option value="{{ $key }}">{{ $val }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-label">
                            Email
                            <span class="text-danger"> *</span>
                        </label>
                        <input type="email" class="form-control mb-3" id="email" name="email" placeholder="alamat email ..." autofocus style="border-radius: 5px !important">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Tutup</button>
                    <button type="submit" class="btn btn-primary">Simpan</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- End Modal Edit -->
@endsection