routes/web.php
<?php

use App\Http\Controllers\Admin\BerandaController;
use App\Http\Controllers\Admin\BeritaController;
use App\Http\Controllers\Admin\CalonSiswaController;
use App\Http\Controllers\Admin\DataSiswaController;
use App\Http\Controllers\Admin\DetailPaketSoalController;
use App\Http\Controllers\Admin\HasilController;
use App\Http\Controllers\Admin\JurusanController;
use App\Http\Controllers\Admin\KeuanganController;
use App\Http\Controllers\Admin\LaporanController;
use App\Http\Controllers\Admin\MasterController;
use App\Http\Controllers\Admin\PaketSoalController;
use App\Http\Controllers\Admin\PendataanAssetController;
use App\Http\Controllers\Admin\PengaturanController;
use App\Http\Controllers\Admin\PersuratanController;
use App\Http\Controllers\Admin\ProfilController;
use App\Http\Controllers\Admin\TestController;
use App\Http\Controllers\Admin\TokenController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\User\BerandaController as UserBerandaController;
use Illuminate\Support\Facades\Route;
use Symfony\Component\HttpKernel\Profiler\Profile;

Route::get('/', function () {
    return redirect()->route('web.beranda');
});

Route::controller(TestController::class)->prefix('test')->name('test.')->group(function () {
    Route::get('/mulai', 'index')->name('index');
    Route::post('/login', 'login')->name('login');
    Route::get('/{token}/{name}/{kelas}/{jurusan}', 'test')->name('test');
    Route::post('/store', 'store')->name('store');
});

Route::controller(UserBerandaController::class)->name('web.')->group(function () {
    Route::get('/', 'index')->name('beranda');
    Route::get('/berita', 'berita')->name('berita');
    Route::get('/data-siswa', 'dataSiswa')->name('dataSiswa');
    Route::get('/berita/{name}', 'lihat_berita')->name('berita.lihat');
    Route::get('/ppdb', 'ppdb')->name('ppdb');
    Route::post('/ppdb/store', 'ppdb_store')->name('ppdb.store');
    Route::get('/ppdb/berhasil-mendaftar/{name}/{id}', 'ppdb_detail')->name('ppdb.detail');
    Route::get('/ppdb/print/{name}/{id}', 'ppdb_print')->name('ppdb.print');
    Route::get('/ppdb/cek-pendaftaran', 'cek_ppdb')->name('ppdb.check');
    Route::get('/ppdb/kartu-lulus/{name}/{id}', 'ppdb_kartu_lulus')->name('ppdb.kartu.lulus');
    Route::get('/ppdb/kartu-lulus/{name}/{id}/print', 'ppdb_kartu_lulus_print')->name('ppdb.kartu.lulus.print');
    Route::get('/ppdb/test', 'test_ppdb')->name('ppdb.test');
});

Route::controller(LoginController::class)->name('auth.')->group(function () {
    Route::get('/login', 'login')->name('login.form');
    Route::post('/login', 'validation')->name('login.validation');
    Route::get('/logout', 'logout')->name('logout');
});

Route::prefix('admin')->name('admin.')->middleware(['auth'])->group(function () {
    // MIDDLEWARE AUTH
    Route::controller(BerandaController::class)->prefix('beranda')->name('beranda.')->group(function () {
        Route::get('/', 'index')->name('index');
    });
    Route::controller(LaporanController::class)->prefix('laporan')->name('laporan.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::get('/print', 'print')->name('print');
    });
    Route::controller(DataSiswaController::class)->prefix('data-siswa')->name('siswa.')->group(function () {
        Route::get('/', 'index')->name('index');
    });
    // END MIDDLEWARE AUTH

    // ADMIN
    Route::controller(UserController::class)->middleware(['user_akses:admin'])->prefix('akun-guru')->name('guru.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::post('/store', 'store')->name('store');
        Route::get('/{id}/destroy', 'destroy')->name('destroy');
        Route::post('/update', 'update')->name('update');
        Route::post('/update/password', 'change_password')->name('update.password');
    });
    // END ADMIN

    // PERSURATAN
    Route::controller(PersuratanController::class)->middleware(['user_akses:admin,persuratan'])->prefix('surat')->name('surat.')->group(function () {
        Route::prefix('diterima')->name('masuk.')->group(function () {
            Route::get('/', 'index_surat_masuk')->name('index');
            Route::get('/{id}/destroy', 'destroy_surat_masuk')->name('destroy');
            Route::get('/{id}/destroy-file', 'destroy_file_surat_masuk')->name('destroy.file');
            Route::get('/tambah-surat-masuk', 'create_surat_masuk')->name('create');
            Route::post('/store', 'store_surat_masuk')->name('store');
            Route::get('/{id}/edit', 'edit_surat_masuk')->name('edit');
            Route::post('/update', 'update_surat_masuk')->name('update');
        });
        Route::prefix('dikirim')->name('keluar.')->group(function () {
            Route::get('/', 'index_surat_keluar')->name('index');
            Route::get('/tambah-surat-keluar', 'create_surat_keluar')->name('create');
            Route::get('/{id}/destroy', 'destroy_surat_keluar')->name('destroy');
            Route::get('/{id}/destroy-file', 'destroy_file_surat_keluar')->name('destroy.file');
            Route::get('/{id}/edit', 'edit_surat_keluar')->name('edit');
            Route::post('/update', 'update_surat_keluar')->name('update');
            Route::get('/tambah-surat-keluar', 'create_surat_keluar')->name('create');
            Route::post('/store', 'store_surat_keluar')->name('store');
        });
    });
    Route::controller(PendataanAssetController::class)->middleware(['user_akses:admin,persuratan'])->prefix('aset')->name('aset.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::get('/{id}/edit', 'edit')->name('edit');
        Route::post('/update', 'update')->name('update');
        Route::get('/{id}/destroy', 'destroy')->name('destroy');
        Route::get('/data-aset-baru', 'create')->name('create');
        Route::post('/store', 'store')->name('store');
        Route::get('/{id}/destroy/gambar_1', 'gambar_1_destory')->name('destory.gambar_1');
        Route::get('/{id}/destroy/gambar_2', 'gambar_2_destory')->name('destory.gambar_2');
        Route::get('/{id}/destroy/gambar_3', 'gambar_3_destory')->name('destory.gambar_3');
    });
    // END PERSURATAN

    // PENGELOLA WEB
    Route::prefix('artikel.')->name('artikel.')->middleware(['user_akses:pengelola_web,admin'])->group(function () {
        Route::controller(BeritaController::class)->prefix('berita')->name('berita.')->group(function () {
            Route::get('/', 'index')->name('index');
            Route::get('/tulis-berita', 'create')->name('create');
            Route::post('/store', 'store')->name('store');
            Route::get('/{id}/destroy', 'destroy')->name('destroy');
            Route::get('/{id}/edit', 'edit')->name('edit');
            Route::post('/{id}/update', 'update')->name('update');
            Route::get('/{id}/destroy/thumbnail', 'thumbnail_destory')->name('destory.thumbnail');
        });
        Route::controller(JurusanController::class)->prefix('peminatan')->name('peminatan.')->group(function () {
            Route::get('/', 'index')->name('index');
            Route::get('/tulis-peminatan', 'create')->name('create');
            Route::post('/store', 'store')->name('store');
            Route::get('/{id}/destroy', 'destroy')->name('destroy');
            Route::get('/{id}/edit', 'edit')->name('edit');
            Route::post('/{id}/update', 'update')->name('update');
            Route::get('/{id}/destroy/thumbnail', 'thumbnail_destory')->name('destory.thumbnail');
        });
        Route::controller(ProfilController::class)->prefix('profil')->name('profil.')->group(function () {
            Route::get('/', 'index')->name('index');
            Route::post('/{id}/update', 'update')->name('update');
            Route::get('/{id}/destroy/thumbnail', 'thumbnail_destory')->name('destory.thumbnail');
        });
    });
    Route::controller(PengaturanController::class)->middleware(['user_akses:pengelola_web,admin,ppdb'])->prefix('pengaturan')->name('pengaturan.')->group(function () {
        Route::get('/instansi', 'instansi')->name('instansi');
        Route::post('/instansi/update', 'instansi_update')->name('instansi.update');
        Route::get('/logo-instansi/destory', 'logo_instansi_destory')->name('instansi.destory.logo');
        Route::get('/foto-carousel-1/destory', 'foto_carousel_1_destory')->name('instansi.destory.carousel_1');
        Route::get('/foto-carousel-2/destory', 'foto_carousel_2_destory')->name('instansi.destory.carousel_2');
        Route::get('/foto-carousel-3/destory', 'foto_carousel_3_destory')->name('instansi.destory.carousel_3');
        Route::get('/foto-kepala/destory', 'foto_kepala_destory')->name('instansi.destory.foto_kepala');
        Route::get('/thumbnail-visi-misi/destory', 'thumbnail_visi_misi_destory')->name('instansi.destory.thumbnail_visi_misi');
    });
    Route::controller(MasterController::class)->middleware(['user_akses:pengelola_web,admin'])->prefix('master')->name('master.')->group(function () {
        Route::prefix('jurusan')->name('jurusan.')->group(function () {
            Route::get('/', 'index_jurusan')->name('index');
            Route::post('/store', 'store_jurusan')->name('store');
            Route::get('/{id}/destroy', 'destroy_jurusan')->name('destroy');
            Route::post('/update', 'update_jurusan')->name('update');
        });
        Route::prefix('kategori')->name('kategori.')->group(function () {
            Route::get('/', 'index_kategori')->name('index');
            Route::post('/store', 'store_kategori')->name('store');
            Route::post('/update', 'update_kategori')->name('update');
            Route::get('/{id}/destroy', 'destroy_kategori')->name('destroy');
        });
    });
    // END PENGELOLA WEB

    // PANITIA PPDB
    Route::middleware(['user_akses:ppdb,admin'])->group(function () {

app/Models/SuratKeluar.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class SuratKeluar extends Model
{
    use HasFactory;
    protected $table = 'db_surat_keluar';
    protected $primaryKey = 'id';
    protected $fillable = [
        'file_surat',
        'petugas',
        'penerima',
        'no_surat',
        'tanggal_keluar',
        'keperluan',
    ];
}

resources/views/admin/persuratan/surat_keluar/create.blade.php
@extends('layouts.dasboard')
@section('css')
    <style></style>
@endsection
@section('script')
    <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.12.1/js/dataTables.bootstrap5.min.js"></script>
    <script>
        $('#data-table').DataTable({
            responsive: true,
            pageLength: 10,
            lengthMenu: [[10, 50, 100, -1], [10, 50, 100, "Semua"]],
            paging: true,
        });
    </script>
@endsection
@section('content')
<form class="forms-sample" action="{{ route('admin.surat.keluar.store') }}" method="POST" enctype="multipart/form-data">
    @csrf
    <div class="row mb-3">
        <div class="col-12 col-md-6 col-lg-6">
            <h3 class="mb-4">Tambah Surat Keluar</h3>
        </div>
        <div class="col-12 col-md-6 col-lg-6">
            <button type="submit" class="btn btn-primary text-white" style="float: right">
                Tambah
            </button>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="row mb-4">
                        <div class="col-12 col-md-4 col-lg-4">
                            <label class="form-label">
                                Nama Penerimaa
                                <span class="text-danger"> *</span>
                            </label>
                            <input type="text" class="form-control" value="{{ old('penerima') }}" style="border-radius: 5px !important" name="penerima" placeholder="nama penerima ..." required>
                        </div>
                        <div class="col-12 col-md-4 col-lg-4">
                            <label class="form-label">
                                Nama Petugas
                                <span class="text-danger"> *</span>
                            </label>
                            <input type="text" class="form-control" value="{{ old('petugas') }}" style="border-radius: 5px !important" name="petugas" placeholder="nama petugas ..." required>
                        </div>
                        <div class="col-12 col-md-4 col-lg-4">
                            <label class="form-label">
                                Nomor Surat
                                <span class="text-danger"> *</span>
                            </label>
                            <input type="text" class="form-control" value="{{ old('no_surat') }}" style="border-radius: 5px !important" name="no_surat" placeholder="nomor surat keluar ..." required>
                        </div>
                    </div>
                    <div class="row mb-4">
                        <div class="col-12">
                            <label class="form-label w-100">
                                Keperluan
                                <span class="text-danger"> *</span>
                            </label>
                            <textarea required class="w-100 form-control" name="keperluan">{{ old('keperluan') }}</textarea>
                        </div>
                    </div>
                    <div class="row mb-4">
                        <div class="col-12 col-md-4 col-lg-4">
                            <label class="form-label">
                                Tanggal Keluar
                                <span class="text-danger"> *</span>
                            </label>
                            <input type="date" class="form-control" value="{{ old('tanggal_keluar') }}" style="border-radius: 5px !important" name="tanggal_keluar" placeholder="mm/dd/yyyy" required>
                        </div>
                        <div class="col-12 col-md-8 col-lg-8">
                            <div class="form-group">
                                <label class="form-label">
                                    File Surat
                                </label>
                                <input type="file" class="form-control" style="border-radius: 5px !important" name="file_surat" placeholder="file surat ..." >
                                <small class="text-danger">
                                    <i>*masksimal 10mb | File bisa berupa file PDF, atau hasil foto dalam sekali jepret</i>
                                </small>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
@endsection

resources/views/admin/persuratan/surat_keluar/edit.blade.php
@extends('layouts.dasboard')
@section('css')
    <style></style>
@endsection
@section('script')
    <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.12.1/js/dataTables.bootstrap5.min.js"></script>
    <script>
        $('#data-table').DataTable({
            responsive: true,
            pageLength: 10,
            lengthMenu: [[10, 50, 100, -1], [10, 50, 100, "Semua"]],
            paging: true,
        });
    </script>
@endsection
@section('content')
<form class="forms-sample" action="{{ route('admin.surat.keluar.update') }}" method="POST" enctype="multipart/form-data">
    @csrf
    <input type="hidden" name="id" value="{{ $data->id }}">
    <div class="row mb-3">
        <div class="col-12 col-md-6 col-lg-6">
            <h3 class="mb-4">Edit Surat untuk {{ $data->penerima }}</h3>
        </div>
        <div class="col-12 col-md-6 col-lg-6">
            <button type="submit" class="btn btn-primary text-white" style="float: right">
                Simpan
            </button>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="row mb-4">
                        <div class="col-12 col-md-4 col-lg-4">
                            <label class="form-label">
                                Nama Penerimaa
                                <span class="text-danger"> *</span>
                            </label>
                            <input type="text" class="form-control" value="{{ $data->penerima }}" style="border-radius: 5px !important" name="penerima" placeholder="nama penerima ..." required>
                        </div>
                        <div class="col-12 col-md-4 col-lg-4">
                            <label class="form-label">
                                Nama Petugas
                                <span class="text-danger"> *</span>
                            </label>
                            <input type="text" class="form-control" value="{{ $data->petugas }}" style="border-radius: 5px !important" name="petugas" placeholder="nama petugas ..." required>
                        </div>
                        <div class="col-12 col-md-4 col-lg-4">
                            <label class="form-label">
                                Nomor Surat
                                <span class="text-danger"> *</span>
                            </label>
                            <input type="text" class="form-control" value="{{ $data->no_surat }}" style="border-radius: 5px !important" name="no_surat" placeholder="nomor surat keluar ..." required>
                        </div>
                    </div>
                    <div class="row mb-4">
                        <div class="col-12">
                            <label class="form-label w-100">
                                Keperluan
                                <span class="text-danger"> *</span>
                            </label>
                            <textarea required class="w-100 form-control" name="keperluan">{{ $data->keperluan == "" ? 'Tulis keperluan disini ...' : $data->keperluan }}</textarea>
                        </div>
                    </div>
                    <div class="row mb-4">
                        <div class="col-12 col-md-4 col-lg-4">
                            <label class="form-label">
                                Tanggal Diterima
                                <span class="text-danger"> *</span>
                            </label>
                            <input type="date" class="form-control" value="{{ $data->tanggal_keluar }}" style="border-radius: 5px !important" name="tanggal_keluar" placeholder="mm/dd/yyyy" required>
                        </div>
                        <div class="col-12 col-md-8 col-lg-8">
                            <div class="form-group">
                                @if ($data->file_surat == "")
                                    <label class="form-label">
                                        File Surat
                                    </label>
                                    <input type="file" class="form-control" style="border-radius: 5px !important" name="file_surat" placeholder="file surat ..." >
                                    <small class="text-danger">
                                        <i>*masksimal 10mb | File bisa berupa file PDF, atau hasil foto dalam sekali jepret</i>
                                    </small>
                                @else
                                    <div class="row mb-2">
                                        <div class="col-12">
                                            <label class="form-label">
                                                File Surat
                                            </label>
                                        </div>
                                        <div class="col-12 d-flex">
                                            <input type="text" class="form-control mr-2" value="{{ $data->file_surat }}" readonly>
                                            <a href="{{ config('constant.path.surat.keluar.file_surat').$data->file_surat }}" download
                                                class="btn btn-success p-1 px-2 mr-1" title="download file surat keluar dari {{ $data->penerima }}"
                                                style="height: 47px !important; min-width: 47px !important;padding-top:10px !important">
                                                <i data-feather="download" width="14"></i>
                                            </a>
                                            <button type="button" class="btn btn-danger p-1 px-2"
                                                title="Hapus file surat dari {{ $data->penerima }}"
                                                onclick="alert_confirm('Hapus file surat dari {{ $data->penerima }}?','{{ route('admin.surat.keluar.destroy.file',['id'=>$data->id]) }}','Hapus','Batal')"
                                                style="height: 47px !important; min-width: 47px !important">
                                                <i data-feather="trash" width="14"></i>
                                            </button>
                                        </div>
                                    </div>
                                @endif
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
@endsection

resources/views/admin/persuratan/surat_keluar/index.blade.php
@extends('layouts.dasboard')
@section('css')
    <style></style>
@endsection
@section('script')
    <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.12.1/js/dataTables.bootstrap5.min.js"></script>
    <script>
        $('#data-table').DataTable({
            responsive: true,
            pageLength: 10,
            lengthMenu: [[10, 50, 100, -1], [10, 50, 100, "Semua"]],
            paging: true,
        });
    </script>
@endsection
@section('content')
<div class="row mb-3">
    <div class="col-12 col-md-6 col-lg-6">
        <h3 class="mb-4">Surat Keluar</h3>
    </div>
    <div class="col-12 col-md-6 col-lg-6">
        <a href="{{ route('admin.surat.keluar.create') }}" class="btn btn-primary text-white" style="float: right">
            Tambah
        </a>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    <table id="data-table" class="table table-hover table-bordered" style="width: 100% !important">
                        <thead>
                            <tr>
                                <th class="text-center" style="width: 30px !important;">No</th>
                                <th>Tgl. Keluar</th>
                                <th>Penerima</th>
                                <th>Petugas</th>
                                <th>Nomor Surat</th>
                                <th>Keperluan</th>
                                <th>Unduh</th>
                                <th class="text-center" style="width: 150px">Opsi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($data as $index => $val)
                                <tr>
                                    <td>{{ ++$index }}</td>
                                    <td>{{ defaultDate($val->tanggal_keluar) }}</td>
                                    <td>{{ $val->penerima }}</td>
                                    <td>{{ $val->petugas }}</td>
                                    <td>{{ $val->no_surat  }}</td>
                                    <td>{{ $val->keperluan }}</td>
                                    <td>
                                        @if ($val->file_surat == null || $val->file_surat == '')
                                            <button type="button" disabled
                                                class="btn btn-light br-1 px-1 mb-1"
                                                style="height: 30px !important; min-width: 30px !important">
                                                <i data-feather="download" width="13"></i>
                                            </button>
                                        @else
                                            <a href="{{ config('constant.path.surat.keluar.file_surat').$val->file_surat }}" download
                                                class="btn btn-secondary br-1 px-1 mb-1" title="download file surat keluar untuk {{ $val->penerima }}"
                                                style="height: 30px !important; min-width: 30px !important">
                                                <i data-feather="download" width="13"></i>
                                            </a>
                                        @endif
                                    </td>
                                    <td>
                                        <a href="{{ route('admin.surat.keluar.edit',['id'=>$val->id]) }}" class="btn btn-primary br-1 px-1 mb-1"
                                            title="Edit surat untuk {{ $val->penerima }}"
                                            style="height: 30px !important; min-width: 30px !important">
                                            <i data-feather="edit" width="13"></i>
                                        </a>
                                        <button type="button" class="btn btn-danger br-1 px-1 mb-1"
                                            title="Hapus surat untuk {{ $val->penerima }}"
                                            onclick="alert_confirm('Hapus surat untuk {{ $val->penerima }}?','{{ route('admin.surat.keluar.destroy',['id'=> $val->id]) }}','Hapus','Batal')"
                                            style="height: 30px !important; min-width: 30px !important">
                                            <i data-feather="trash" width="13"></i>
                                        </button>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection