routes/web.php
<?php

use App\Http\Controllers\Admin\BerandaController;
use App\Http\Controllers\Admin\BeritaController;
use App\Http\Controllers\Admin\CalonSiswaController;
use App\Http\Controllers\Admin\DataSiswaController;
use App\Http\Controllers\Admin\DetailPaketSoalController;
use App\Http\Controllers\Admin\HasilController;
use App\Http\Controllers\Admin\JurusanController;
use App\Http\Controllers\Admin\KeuanganController;
use App\Http\Controllers\Admin\LaporanController;
use App\Http\Controllers\Admin\MasterController;
use App\Http\Controllers\Admin\PaketSoalController;
use App\Http\Controllers\Admin\PendataanAssetController;
use App\Http\Controllers\Admin\PengaturanController;
use App\Http\Controllers\Admin\PersuratanController;
use App\Http\Controllers\Admin\ProfilController;
use App\Http\Controllers\Admin\TestController;
use App\Http\Controllers\Admin\TokenController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\User\BerandaController as UserBerandaController;
use Illuminate\Support\Facades\Route;
use Symfony\Component\HttpKernel\Profiler\Profile;

Route::get('/', function () {
    return redirect()->route('web.beranda');
});

Route::controller(TestController::class)->prefix('test')->name('test.')->group(function () {
    Route::get('/mulai', 'index')->name('index');
    Route::post('/login', 'login')->name('login');
    Route::get('/{token}/{name}/{kelas}/{jurusan}', 'test')->name('test');
    Route::post('/store', 'store')->name('store');
});

Route::controller(UserBerandaController::class)->name('web.')->group(function () {
    Route::get('/', 'index')->name('beranda');
    Route::get('/berita', 'berita')->name('berita');
    Route::get('/data-siswa', 'dataSiswa')->name('dataSiswa');
    Route::get('/berita/{name}', 'lihat_berita')->name('berita.lihat');
    Route::get('/ppdb', 'ppdb')->name('ppdb');
    Route::post('/ppdb/store', 'ppdb_store')->name('ppdb.store');
    Route::get('/ppdb/berhasil-mendaftar/{name}/{id}', 'ppdb_detail')->name('ppdb.detail');
    Route::get('/ppdb/print/{name}/{id}', 'ppdb_print')->name('ppdb.print');
    Route::get('/ppdb/cek-pendaftaran', 'cek_ppdb')->name('ppdb.check');
    Route::get('/ppdb/kartu-lulus/{name}/{id}', 'ppdb_kartu_lulus')->name('ppdb.kartu.lulus');
    Route::get('/ppdb/kartu-lulus/{name}/{id}/print', 'ppdb_kartu_lulus_print')->name('ppdb.kartu.lulus.print');
    Route::get('/ppdb/test', 'test_ppdb')->name('ppdb.test');
});

Route::controller(LoginController::class)->name('auth.')->group(function () {
    Route::get('/login', 'login')->name('login.form');
    Route::post('/login', 'validation')->name('login.validation');
    Route::get('/logout', 'logout')->name('logout');
});

Route::prefix('admin')->name('admin.')->middleware(['auth'])->group(function () {
    // MIDDLEWARE AUTH
    Route::controller(BerandaController::class)->prefix('beranda')->name('beranda.')->group(function () {
        Route::get('/', 'index')->name('index');
    });
    Route::controller(LaporanController::class)->prefix('laporan')->name('laporan.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::get('/print', 'print')->name('print');
    });
    Route::controller(DataSiswaController::class)->prefix('data-siswa')->name('siswa.')->group(function () {
        Route::get('/', 'index')->name('index');
    });
    // END MIDDLEWARE AUTH

    // ADMIN
    Route::controller(UserController::class)->middleware(['user_akses:admin'])->prefix('akun-guru')->name('guru.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::post('/store', 'store')->name('store');
        Route::get('/{id}/destroy', 'destroy')->name('destroy');
        Route::post('/update', 'update')->name('update');
        Route::post('/update/password', 'change_password')->name('update.password');
    });
    // END ADMIN

    // PERSURATAN
    Route::controller(PersuratanController::class)->middleware(['user_akses:admin,persuratan'])->prefix('surat')->name('surat.')->group(function () {
        Route::prefix('diterima')->name('masuk.')->group(function () {
            Route::get('/', 'index_surat_masuk')->name('index');
            Route::get('/{id}/destroy', 'destroy_surat_masuk')->name('destroy');
            Route::get('/{id}/destroy-file', 'destroy_file_surat_masuk')->name('destroy.file');
            Route::get('/tambah-surat-masuk', 'create_surat_masuk')->name('create');
            Route::post('/store', 'store_surat_masuk')->name('store');
            Route::get('/{id}/edit', 'edit_surat_masuk')->name('edit');
            Route::post('/update', 'update_surat_masuk')->name('update');
        });
        Route::prefix('dikirim')->name('keluar.')->group(function () {
            Route::get('/', 'index_surat_keluar')->name('index');
            Route::get('/tambah-surat-keluar', 'create_surat_keluar')->name('create');
            Route::get('/{id}/destroy', 'destroy_surat_keluar')->name('destroy');
            Route::get('/{id}/destroy-file', 'destroy_file_surat_keluar')->name('destroy.file');
            Route::get('/{id}/edit', 'edit_surat_keluar')->name('edit');
            Route::post('/update', 'update_surat_keluar')->name('update');
            Route::get('/tambah-surat-keluar', 'create_surat_keluar')->name('create');
            Route::post('/store', 'store_surat_keluar')->name('store');
        });
    });
    Route::controller(PendataanAssetController::class)->middleware(['user_akses:admin,persuratan'])->prefix('aset')->name('aset.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::get('/{id}/edit', 'edit')->name('edit');
        Route::post('/update', 'update')->name('update');
        Route::get('/{id}/destroy', 'destroy')->name('destroy');
        Route::get('/data-aset-baru', 'create')->name('create');
        Route::post('/store', 'store')->name('store');
        Route::get('/{id}/destroy/gambar_1', 'gambar_1_destory')->name('destory.gambar_1');
        Route::get('/{id}/destroy/gambar_2', 'gambar_2_destory')->name('destory.gambar_2');
        Route::get('/{id}/destroy/gambar_3', 'gambar_3_destory')->name('destory.gambar_3');
    });
    // END PERSURATAN

    // PENGELOLA WEB
    Route::prefix('artikel.')->name('artikel.')->middleware(['user_akses:pengelola_web,admin'])->group(function () {
        Route::controller(BeritaController::class)->prefix('berita')->name('berita.')->group(function () {
            Route::get('/', 'index')->name('index');
            Route::get('/tulis-berita', 'create')->name('create');
            Route::post('/store', 'store')->name('store');
            Route::get('/{id}/destroy', 'destroy')->name('destroy');
            Route::get('/{id}/edit', 'edit')->name('edit');
            Route::post('/{id}/update', 'update')->name('update');
            Route::get('/{id}/destroy/thumbnail', 'thumbnail_destory')->name('destory.thumbnail');
        });
        Route::controller(JurusanController::class)->prefix('peminatan')->name('peminatan.')->group(function () {
            Route::get('/', 'index')->name('index');
            Route::get('/tulis-peminatan', 'create')->name('create');
            Route::post('/store', 'store')->name('store');
            Route::get('/{id}/destroy', 'destroy')->name('destroy');
            Route::get('/{id}/edit', 'edit')->name('edit');
            Route::post('/{id}/update', 'update')->name('update');
            Route::get('/{id}/destroy/thumbnail', 'thumbnail_destory')->name('destory.thumbnail');
        });
        Route::controller(ProfilController::class)->prefix('profil')->name('profil.')->group(function () {
            Route::get('/', 'index')->name('index');
            Route::post('/{id}/update', 'update')->name('update');
            Route::get('/{id}/destroy/thumbnail', 'thumbnail_destory')->name('destory.thumbnail');
        });
    });
    Route::controller(PengaturanController::class)->middleware(['user_akses:pengelola_web,admin,ppdb'])->prefix('pengaturan')->name('pengaturan.')->group(function () {
        Route::get('/instansi', 'instansi')->name('instansi');
        Route::post('/instansi/update', 'instansi_update')->name('instansi.update');
        Route::get('/logo-instansi/destory', 'logo_instansi_destory')->name('instansi.destory.logo');
        Route::get('/foto-carousel-1/destory', 'foto_carousel_1_destory')->name('instansi.destory.carousel_1');
        Route::get('/foto-carousel-2/destory', 'foto_carousel_2_destory')->name('instansi.destory.carousel_2');
        Route::get('/foto-carousel-3/destory', 'foto_carousel_3_destory')->name('instansi.destory.carousel_3');
        Route::get('/foto-kepala/destory', 'foto_kepala_destory')->name('instansi.destory.foto_kepala');
        Route::get('/thumbnail-visi-misi/destory', 'thumbnail_visi_misi_destory')->name('instansi.destory.thumbnail_visi_misi');
    });
    Route::controller(MasterController::class)->middleware(['user_akses:pengelola_web,admin'])->prefix('master')->name('master.')->group(function () {
        Route::prefix('jurusan')->name('jurusan.')->group(function () {
            Route::get('/', 'index_jurusan')->name('index');
            Route::post('/store', 'store_jurusan')->name('store');
            Route::get('/{id}/destroy', 'destroy_jurusan')->name('destroy');
            Route::post('/update', 'update_jurusan')->name('update');
        });
        Route::prefix('kategori')->name('kategori.')->group(function () {
            Route::get('/', 'index_kategori')->name('index');
            Route::post('/store', 'store_kategori')->name('store');
            Route::post('/update', 'update_kategori')->name('update');
            Route::get('/{id}/destroy', 'destroy_kategori')->name('destroy');
        });
    });
    // END PENGELOLA WEB

    // PANITIA PPDB
    Route::middleware(['user_akses:ppdb,admin'])->group(function () {

app/Models/Jurusan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Jurusan extends Model
{
    use HasFactory;
    protected $table = 'ms_jurusan';
    protected $primaryKey = 'id';
    protected $fillable = [
        'nama_jurusan',
        'status',
        'kode',
    ];
}

app/Http/Controllers/Admin/JurusanController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Berita;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class JurusanController extends Controller
{
    public function index()
    {
        $data = Berita::query()->join('ms_kategori as a', 'a.id', 'db_berita.id_kategori')
            ->where('id_kategori', '2')
            ->select('db_berita.*', 'a.nama_kategori')
            ->orderBy('id', 'DESC')->get();
        return view('admin.artikel.peminatan.index', compact('data'));
    }
    public function create()
    {
        return view('admin.artikel.peminatan.create');
    }
    public function store(Request $request)
    {
        $request->validate(
            [
                'judul' => 'required',
                'penulis' => 'required',
                'sinopsis' => 'required',
                'konten' => 'required',
                'status' => 'required',
                'kata_kunci' => 'required',
            ],
            [
                'required' => ":attribute belum diisi",
            ],
            [
                'sinopsis' => 'slug/sinopsis',
                'konten' => 'isi konten',
                'kata_kunci' => 'kata kunci',
            ]
        );
        try {
            $data = Berita::create([
                'judul' => $request->judul,
                'penulis' => $request->penulis,
                'sinopsis' => $request->sinopsis,
                'konten' => $request->konten,
                'id_kategori' => 2,
                'status' => $request->status,
                'kata_kunci' => $request->kata_kunci,
                'thumbnail' => $request->thumbnail,
            ]);
            if ($request->hasFile('thumbnail')) {
                $file = $request->file('thumbnail');
                $request->validate([
                    'thumbnail' => 'required|image|mimes:jpeg,png,jpg',
                ]);
                $filename = date('dmyHis') . '_thumbnail' . '.' . $file->getClientOriginalExtension();
                Storage::disk('public')->put(config('constant.path.storage.peminatan.thumbnail') .  $filename, file_get_contents($file));
                $data->thumbnail = $filename;
                $data->save();
            }
            return redirect()->route('admin.artikel.peminatan.index')->with('success', 'Berhasil menambahkan peminatan');
        } catch (\Throwable $th) {
            return redirect()->back()->with('error', 'Kesalahan sistem');
        }
    }
    public function edit($id)
    {
        $data = Berita::find($id);
        return view('admin.artikel.peminatan.edit', compact('data'));
    }
    public function update($id, Request $request)
    {
        $request->validate(
            [
                'judul' => 'required',
                'penulis' => 'required',
                'sinopsis' => 'required',
                'konten' => 'required',
                'status' => 'required',
                'kata_kunci' => 'required',
            ],
            [
                'required' => ":attribute belum diisi",
            ],
            [
                'sinopsis' => 'slug/sinopsis',
                'konten' => 'isi konten',
                'kata_kunci' => 'kata kunci',
            ]
        );
        try {
            $data = Berita::find($id);
            $data->update([
                'judul' => $request->judul,
                'penulis' => $request->penulis,
                'sinopsis' => $request->sinopsis,
                'konten' => $request->konten,
                'id_kategori' => 2,
                'status' => $request->status,
                'kata_kunci' => $request->kata_kunci,
            ]);
            if ($request->hasFile('thumbnail')) {
                $file = $request->file('thumbnail');
                $request->validate([
                    'thumbnail' => 'required|image|mimes:jpeg,png,jpg',
                ]);
                $filename = date('dmyHis') . '_thumbnail' . '.' . $file->getClientOriginalExtension();
                Storage::disk('public')->put(config('constant.path.storage.peminatan.thumbnail') .  $filename, file_get_contents($file));
                $data->thumbnail = $filename;
                $data->save();
            }
            return redirect()->route('admin.artikel.peminatan.index')->with('success', 'Berhasil memperbarui peminatan');
        } catch (\Throwable $th) {
            return redirect()->back()->with('error', 'Kesalahan sistem');
        }
    }
    public function destroy($id)
    {
        try {
            $data = Berita::find($id);
            $nama = $data->judul;
            $data->delete($data);
            return redirect()->back()->with('success', $nama . ' berhasil dihapus');
        } catch (\Throwable $th) {
            return redirect()->back()->with('error', 'Kesalahan sistem');
        }
    }
    public function thumbnail_destory($id)
    {
        try {
            $data = Berita::find($id);
            Storage::disk('public')->delete(config('constant.path.storage.peminatan.thumbnail') .  $data->thumbnail);
            $data->update([
                'thumbnail' => '',
            ]);
            return redirect()->back()->with('success', 'Berhasil menghapus thumbnail');
        } catch (\Throwable $th) {
            return redirect()->back()->with('error', 'Gagal, Kesalahan sistem');
        }
    }
}

resources/views/admin/master/jurusan/index.blade.php
@extends('layouts.dasboard')
@section('css')
@endsection
@section('script')
    <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.12.1/js/dataTables.bootstrap5.min.js"></script>
    <script>
        $('#data-table').DataTable({
            responsive: true,
            pageLength: 10,
            lengthMenu: [[10, 50, 100, -1], [10, 50, 100, "Semua"]],
            paging: true,
        });
        function dataModal(data){
            console.log(JSON.parse(data))
            var data = JSON.parse(data)
            $('#id_jurusan').val(data.id)
            $('#edit_nama_jurusan').val(data.nama_jurusan)
            $('#edit_kode').val(data.kode)
        }
    </script>
@endsection
@section('content')
<h3 class="mb-4">Jurusan</h3>
<div class="row">
    <div class="col-12 col-md-4 col-lg-4 order-1 order-md-2 order-lg-2 mb-3">
        <div class="card">
            <div class="card-header">
                <h4 class="form-label mb-2">Tambah data</h4>
            </div>
            <div class="card-body">
                <form class="forms-sample" action="{{ route('admin.master.jurusan.store') }}" method="POST">
                    @csrf
                    <div class="form-group">
                        <label for="nama_jurusan" class="form-label">
                            Nama Jurusan
                            <span class="text-danger"> *</span>
                        </label>
                        <input type="text" class="form-control mb-3" name="nama_jurusan" id="nama_jurusan" placeholder="nama jurusan ..." autofocus style="border-radius: 5px !important">
                    </div>
                    <div class="form-group">
                        <label for="kode" class="form-label">
                            Kode/Singkatan
                            <span class="text-danger"> *</span>
                        </label>
                        <input type="text" class="form-control mb-3" name="kode" id="kode" placeholder="kode/singkatan ..." style="border-radius: 5px !important">
                    </div>
                    <button type="submit" class="btn btn-primary mr-2">Tambah</button>
                </form>
            </div>
        </div>
    </div>
    <div class="col-12 col-md-8 col-lg-8 order-2 order-md-1 order-lg-1 mb-3">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    <table id="data-table" class="table table table-hover table-bordered" style="width: 100% !important">
                        <thead>
                            <tr>
                                <th class="text-center" style="width: 30px !important;">No</th>
                                <th>Kode</th>
                                <th>Nama Jurusan</th>
                                <th class="text-center">Opsi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($data as $index => $val)
                                <tr>
                                    <td class="text-center">{{ ++$index }}</td>
                                    <td>{{ $val->kode }}</td>
                                    <td>{{ eachUpperCase($val->nama_jurusan) }}</td>
                                    <td class="text-center">
                                        <button type="button" class="btn btn-primary br-1 px-1 mb-1"
                                            title="Edit {{ $val->nama_jurusan }}"
                                            onclick="dataModal('{{ json_encode($val) }}')"
                                            data-toggle="modal" data-target="#modalEdit"
                                            style="height: 30px !important; min-width: 30px !important">
                                            <i data-feather="edit" width="13"></i>
                                        </button>
                                        <button type="button" class="btn btn-danger br-1 px-1 mb-1"
                                            title="Hapus {{ $val->nama_jurusan }}"
                                            onclick="alert_confirm('Hapus {{ $val->nama_jurusan }}?','{{ route('admin.master.jurusan.destroy',['id'=> $val->id]) }}','Hapus','Batal')"
                                            style="height: 30px !important; min-width: 30px !important">
                                            <i data-feather="trash" width="13"></i>
                                        </button>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Modal Edit -->
<div class="modal fade" id="modalEdit" tabindex="-1" role="dialog" aria-labelledby="modalEditLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content br-2">
            <form class="forms-sample" action="{{ route('admin.master.jurusan.update') }}" method="POST">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalEditLabel">Edit Jurusan</h5>
                </div>
                <div class="modal-body">
                    @csrf
                    <input type="hidden" name="id" id="id_jurusan">
                    <div class="form-group">
                        <label for="edit_nama_jurusan" class="form-label">
                            Nama Jurusan
                            <span class="text-danger"> *</span>
                        </label>
                        <input type="text" class="form-control mb-3" name="nama_jurusan" id="edit_nama_jurusan" placeholder="nama jurusan ..." autofocus style="border-radius: 5px !important">
                    </div>
                    <div class="form-group">
                        <label for="edit_kode" class="form-label">
                            Kode/Singkatan
                            <span class="text-danger"> *</span>
                        </label>
                        <input type="text" class="form-control" name="kode" id="edit_kode" placeholder="kode/singkatan ..." style="border-radius: 5px !important">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Tutup</button>
                    <button type="submit" class="btn btn-primary">Simpan</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- End Modal Edit -->
@endsection